name: "Run flake8 with reviewdog"
description: "🐶 Run flake8 with reviewdog on pull requests to improve code review experience."
author: "Rick Staa"
inputs:
  workdir:
    description: "Working directory relative to the root directory."
    required: false
    default: "."
  flake8_args:
    description: "Additional flake8 arguments."
    required: false
    default: ""
  # Reviewdog related inputs
  github_token:
    description: "GITHUB_TOKEN."
    required: true
    default: ${{ github.token }}
  tool_name:
    description: "Tool name to use for reviewdog reporter."
    required: false
    default: "flake8"
  error_format:
    description: "Pre-defined error format [flake8, pep8]"
    required: false
    default: "flake8"
  level:
    description: "Report level for reviewdog [info, warning, error]."
    required: false
    default: "error"
  reporter:
    description: "Reporter of reviewdog command [github-pr-check, github-pr-review, github-check]."
    required: false
    default: "github-pr-check"
  filter_mode:
    description: "Filtering mode for the reviewdog command [added, diff_context, file, nofilter]."
    required: false
    default: "added"
  fail_level:
    description: |
      If set to `none`, always use exit code 0 for reviewdog. Otherwise, exit code 1 for reviewdog if it finds at least 1 issue with severity greater than or equal to the given level.
      Possible values: [none,any,info,warning,error]
      Default is `none`.
    default: 'none'
  fail_on_error:
    description: "Deprecated, use `fail_level` instead. Exit code for reviewdog when errors are found [true, false]."
    deprecationMessage: Deprecated, use `fail_level` instead.
    required: false
    default: "false"
  reviewdog_flags:
    description: "Additional reviewdog flags."
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/entrypoint.sh
      shell: bash
      env:
        INPUT_WORKDIR: ${{ inputs.workdir }}
        INPUT_FLAKE8_ARGS: ${{ inputs.flake8_Args }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_TOOL_NAME: ${{ inputs.tool_name }}
        INPUT_ERROR_FORMAT: ${{ inputs.error_format }}
        INPUT_LEVEL: ${{ inputs.level }}
        INPUT_REPORTER: ${{ inputs.reporter }}
        INPUT_FILTER_MODE: ${{ inputs.filter_mode }}
        INPUT_FAIL_LEVEL: ${{ inputs.fail_level }}
        INPUT_FAIL_ON_ERROR: ${{ inputs.fail_on_error }}
        INPUT_REVIEWDOG_FLAGS: ${{ inputs.reviewdog_flags }}

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: "check"
  color: "blue"
