name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test-check:
    name: runner / flake8 (github-check)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Python ${{ matrix.python-version }} environment
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Python environment report
        run: python -c "import sys; print(sys.version)"
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: info
          workdir: ./testdata/

  test-pr-check:
    if: github.event_name == 'pull_request'
    name: runner / flake8 (github-pr-check)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Python ${{ matrix.python-version }} environment
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Python environment report
        run: python -c "import sys; print(sys.version)"
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          level: warning
          workdir: ./testdata/

  test-pr-review:
    if: github.event_name == 'pull_request'
    name: runner / flake8 (github-pr-review)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Python ${{ matrix.python-version }} environment
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Python environment report
        run: python -c "import sys; print(sys.version)"
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: error
          reviewdog_flags: -filter-mode=file # -fail-on-error # NOTE: Disabled due to bug https://github.com/reviewdog/reviewdog/issues/848
          workdir: ./testdata/
